### ISSUE TITLE
Ubuntu GNOME 15.04 and xUbuntu

### ISSUE THREAD

**Issue by grigio** [Distroshare/haswell_chromebook_updates#1]
Hi, I use some of your tweaks copying manually the files I want. Is there a way to include this PPA repo in a clean way in an existing xUbuntu installation?
Thanks

**Comment by hugegreenbug** [comment]
Luigi,

Sorry, I don't have ppa for the config files. However, I have created
an updater script that will copy everything over automatically and
pull in new updates.

Put the following in a new file in: /etc/apt/sources.list.d

deb http://www.distroshare.com/apt trusty main
deb-src http://www.distroshare.com/apt trusty main
deb http://www.distroshare.com/apt_haswell trusty main
deb-src http://www.distroshare.com/apt_haswell trusty main

Then: sudo apt-get update && sudo apt-get install distroshare-ubuntu-updater

After it is installed, you can run it like this:

sudo distroshare-updater
Hugh

**Comment by grigio** [comment]
It seems the python2-git bindings are missing as dependency, I get:

```
❯ sudo distroshare-updater
Traceback (most recent call last):
  File "/usr/sbin/distroshare-updater", line 6, in <module>
    from distroshare_updater.updates import GitRepos
  File "/usr/lib/python2.7/dist-packages/distroshare_updater/updates.py", line 1, in <module>
    from git import Repo
  File "/usr/lib/python2.7/dist-packages/git/__init__.py", line 29, in <module>
    _init_externals()
  File "/usr/lib/python2.7/dist-packages/git/__init__.py", line 23, in _init_externals
    raise ImportError("'gitdb' could not be found in your PYTHONPATH")
ImportError: 'gitdb' could not be found in your PYTHONPATH

```

I've also imported your gpg key with:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv DE55F23DCCE60964
```

and I have:

```
❯ cat /etc/apt/sources.list.d/distroshare.list                                                       ⏎
deb http://www.distroshare.com/apt vivid main
deb http://www.distroshare.com/apt_haswell vivid main
```

**Comment by grigio** [comment]
also `python-gitdb` is present

**Comment by hugegreenbug** [comment]
Those dependencies should install automatically. I don't have a package for
i386 for gitdb, so maybe that is the problem.

Hugh

**Comment by hugegreenbug** [comment]
Did it install from my repo?

Hugh

**Comment by grigio** [comment]
yes distroshare-updater is installed correctly and the deps seems to be there

```
ls /usr/lib/python2.7/dist-packages/git*
/usr/lib/python2.7/dist-packages/gitdb-0.6.4.egg-info

/usr/lib/python2.7/dist-packages/git:
index    repo    cmd.pyc     config.py   db.pyc    exc.py       __init__.pyc  remote.py   util.pyc
objects  test    compat.py   config.pyc  diff.py   exc.pyc      odict.py      remote.pyc
refs     cmd.py  compat.pyc  db.py       diff.pyc  __init__.py  odict.pyc     util.py

/usr/lib/python2.7/dist-packages/gitdb:
db    utils    base.pyc  const.pyc  exc.pyc  fun.pyc      __init__.pyc  pack.pyc  stream.py   typ.py   util.py
test  base.py  const.py  exc.py     fun.py   __init__.py  pack.py       _perf.so  stream.pyc  typ.pyc  util.pyc

/usr/lib/python2.7/dist-packages/GitPython-0.3.6.egg-info:
dependency_links.txt  not-zip-safe  PKG-INFO  requires.txt  SOURCES.txt  top_level.txt
```

**Comment by grigio** [comment]
the other deps came from ubuntu 15.04

**Comment by hugegreenbug** [comment]
It looks correct. I'm not sure what is wrong. Did python-smmap get
installed?

Hugh

**Comment by grigio** [comment]
ok installed `python-smmap` manually and the script starts :)

**Comment by grigio** [comment]
I get this error in the middle

```
Adding any repos listed
Rsyncing distro specific config files
Running apt-get update
Running apt-get dist-upgrade
Installing packages and putting packages on hold
Rsyncing common config files
Rsyncing machine specific config files
Error running command rsync: rsync: change_dir "/var/lib/distroshare-updater/updates/dev" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]

Updating Grub
Updating Initramfs
Updating the version number in /etc/distroshare_release
```

**Comment by hugegreenbug** [comment]
That's ok. It tries to detect your distro and copy specific files for it.
There are none, so it printed an error. I need to suppress that error.

Hugh

**Comment by grigio** [comment]
Thanks for the support `distroshare-ubuntu-updater` override all the files, but it's ok and it works without my hacks :)

**Comment by hugegreenbug** [comment]
Yes, it overwrites the files. Sorry about that, it isn't smart enough to
know that you made changes.

Hugh
